version: '3.4'

services:
  nginx:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - "443:443"
    depends_on:
      - keycloak
    volumes:
      - ./config/nginx:/etc/nginx/conf.d
      - ./data/nginx:/var/log/nginx
      - ./nginx:/var/www/html
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./config/nginx.pem:/etc/nginx/nginx.pem:ro
      - ./config/nginx.key:/etc/nginx/nginx.key:ro

  keycloak:
    image: quay.io/keycloak/keycloak:21.1.0
    restart: unless-stopped
    depends_on:
      - mysql
    ports:
      - 8080:8080
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      PROXY_ADDRESS_FORWARDING: true
      KC_DB: mysql
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KC_DB_URL_HOST: mysql
      KC_DB_URL_PORT: 3306
      KC_DB_SCHEMA: keycloak
      KC_PROXY: edge
      # KEYCLOAK_USER: admin
      # KEYCLOAK_PASSWORD: Pa55w0rd
    command:
      - start-dev

  mysql:
    image: mysql:8.0
    ports:
      - 3366:3306
    restart: unless-stopped
    environment:
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: keycloak
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root
    links:
      - mysql
    ports:
      - 4040:80
    volumes:
      - ./data/phpmyadmin/sessions:/sessions